### ISSUE TITLE
How do you connect it with Drizzle ORM together with Vercel Postgres?

### ISSUE THREAD

**Issue by mmikhan** [TimoWilhelm/local-neon-http-proxy#7]
Hey, couldn't figure out how to connect it with Drizzle ORM with Vercel Postgres. The example is shown [here](https://orm.drizzle.team/docs/tutorials/drizzle-with-vercel-edge-functions#connect-drizzle-orm-to-your-database-1):

```javascript
import { sql } from '@vercel/postgres';
import { drizzle } from 'drizzle-orm/vercel-postgres';

export const db = drizzle(sql)
```

But, the `sql` you show in your example is from the `neon()` function instead of taking it from `@vercel/postgres`:

```javascript
import { neon, neonConfig } from '@neondatabase/serverless';

const connectionString = 'postgres://postgres:postgres@db.localtest.me:5432/main';

neonConfig.fetchEndpoint = (host) => {
  const [protocol, port] = host === 'db.localtest.me' ? ['http', 4444] : ['https', 443];
  return `${protocol}://${host}:${port}/sql`;
};

const sql = neon(connectionString);
const [result] = await sql`SELECT * FROM NOW()`;
```

Any clue?

**Comment by TimoWilhelm** [comment]
This repo only works with the **HTTP** proxy (`@neondatabase/serverless`) not with other (TCP or WebSocket) connections.

Connecting with `@vercel/postgres` is not in scope for this project.

To connect with drizzle using `@neondatabase/serverless` you can use the the `drizzle-orm/neon-http` package.
